-- MEDIFLOW clinic reset RPCs.
-- Backup is generated by the app as an offline HTML file before execute_clinic_reset_json is called.

create or replace function public.reset_has_group(p_groups text[], p_group text)
returns boolean
language sql
immutable
as $$
  select p_group = any(coalesce(p_groups, array[]::text[]))
$$;

create or replace function public.preview_clinic_reset_json(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid := nullif(p_payload->>'organization_id', '')::uuid;
  v_mode text := coalesce(nullif(p_payload->>'reset_mode', ''), 'full');
  v_from date := nullif(p_payload->>'date_from', '')::date;
  v_to date := nullif(p_payload->>'date_to', '')::date;
  v_groups text[] := coalesce(array(select jsonb_array_elements_text(p_payload->'groups')), array[]::text[]);
  v_result jsonb := '{}'::jsonb;
begin
  if not public.is_software_owner() then raise exception 'Only software owner can reset clinic data'; end if;
  if v_org_id is null then raise exception 'Clinic is required'; end if;
  if v_mode <> 'full' and (v_from is null or v_to is null) then raise exception 'Date range is required'; end if;
  if v_mode <> 'full' and (
    public.reset_has_group(v_groups,'patients') or public.reset_has_group(v_groups,'products') or
    public.reset_has_group(v_groups,'suppliers') or public.reset_has_group(v_groups,'doctors') or
    public.reset_has_group(v_groups,'non_admin_users')
  ) then
    raise exception 'Patient, product, supplier, doctor and user master data can only be removed in full reset';
  end if;

  if public.reset_has_group(v_groups,'sales') then
    v_result := v_result || jsonb_build_object(
      'sales',(select count(*) from public.sales where organization_id=v_org_id and (v_mode='full' or sold_at::date between v_from and v_to)),
      'sale_items',(select count(*) from public.sale_items si where si.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.sales s where s.id=si.sale_id and s.sold_at::date between v_from and v_to))),
      'payments',(select count(*) from public.payments where organization_id=v_org_id and (v_mode='full' or paid_at::date between v_from and v_to))
    );
  end if;
  if public.reset_has_group(v_groups,'purchases') then
    v_result := v_result || jsonb_build_object(
      'purchases',(select count(*) from public.purchases where organization_id=v_org_id and (v_mode='full' or invoice_date between v_from and v_to)),
      'purchase_items',(select count(*) from public.purchase_items pi where pi.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.purchases p where p.id=pi.purchase_id and p.invoice_date between v_from and v_to)))
    );
  end if;
  if public.reset_has_group(v_groups,'patient_history') then
    v_result := v_result || jsonb_build_object(
      'consultations',(select count(*) from public.consultations where organization_id=v_org_id and (v_mode='full' or visited_at::date between v_from and v_to)),
      'prescription_attachments',(select count(*) from public.prescription_attachments pa where pa.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.consultations c where c.id=pa.consultation_id and c.visited_at::date between v_from and v_to)))
    );
  end if;
  if public.reset_has_group(v_groups,'patients') then
    v_result := v_result || jsonb_build_object('patients',(select count(*) from public.patients where organization_id=v_org_id));
  end if;
  if public.reset_has_group(v_groups,'inventory') then
    v_result := v_result || jsonb_build_object(
      'stock_movements',(select count(*) from public.stock_movements where organization_id=v_org_id and (v_mode='full' or occurred_at::date between v_from and v_to)),
      'medicine_batches',(select count(*) from public.medicine_batches where organization_id=v_org_id and v_mode='full')
    );
  end if;
  if public.reset_has_group(v_groups,'suppliers') then
    v_result := v_result || jsonb_build_object('suppliers',(select count(*) from public.suppliers where organization_id=v_org_id));
  end if;
  if public.reset_has_group(v_groups,'products') then
    v_result := v_result || jsonb_build_object('products',(select count(*) from public.products where organization_id=v_org_id));
  end if;
  if public.reset_has_group(v_groups,'supplier_accounts') then
    v_result := v_result || jsonb_build_object(
      'supplier_payments',(select count(*) from public.supplier_payments where organization_id=v_org_id and (v_mode='full' or paid_on between v_from and v_to)),
      'supplier_ledger',(select count(*) from public.supplier_ledger where organization_id=v_org_id and (v_mode='full' or occurred_on between v_from and v_to))
    );
  end if;
  if public.reset_has_group(v_groups,'cash_ledger') then
    v_result := v_result || jsonb_build_object(
      'cash_ledger',(select count(*) from public.cash_ledger where organization_id=v_org_id and (v_mode='full' or occurred_at::date between v_from and v_to)),
      'daily_closings',(select count(*) from public.daily_closings where organization_id=v_org_id and (v_mode='full' or closing_date between v_from and v_to))
    );
  end if;
  if public.reset_has_group(v_groups,'accounting') then
    v_result := v_result || jsonb_build_object(
      'journal_entries',(select count(*) from public.journal_entries where organization_id=v_org_id and (v_mode='full' or entry_date between v_from and v_to)),
      'journal_lines',(select count(*) from public.journal_lines jl where jl.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.journal_entries je where je.id=jl.journal_entry_id and je.entry_date between v_from and v_to))),
      'account_ledgers',(select count(*) from public.account_ledgers where organization_id=v_org_id and v_mode='full'),
      'ledger_groups',(select count(*) from public.ledger_groups where organization_id=v_org_id and v_mode='full')
    );
  end if;
  if public.reset_has_group(v_groups,'expenses') then
    v_result := v_result || jsonb_build_object('expenses',(select count(*) from public.expenses where organization_id=v_org_id and (v_mode='full' or expense_date between v_from and v_to)));
  end if;
  if public.reset_has_group(v_groups,'deleted_audit') then
    v_result := v_result || jsonb_build_object(
      'deleted_sales_audit',(select count(*) from public.deleted_sales_audit where organization_id=v_org_id and (v_mode='full' or deleted_at::date between v_from and v_to)),
      'deleted_purchases_audit',(select count(*) from public.deleted_purchases_audit where organization_id=v_org_id and (v_mode='full' or deleted_at::date between v_from and v_to))
    );
  end if;
  if public.reset_has_group(v_groups,'notifications') then
    v_result := v_result || jsonb_build_object('notifications',(select count(*) from public.notifications where organization_id=v_org_id));
  end if;
  if public.reset_has_group(v_groups,'doctors') then
    v_result := v_result || jsonb_build_object('doctors',(select count(*) from public.doctors where organization_id=v_org_id));
  end if;
  if public.reset_has_group(v_groups,'non_admin_users') then
    v_result := v_result || jsonb_build_object(
      'profiles',(select count(*) from public.profiles where organization_id=v_org_id and role <> 'admin'::public.app_role),
      'user_invites',(select count(*) from public.user_invites where organization_id=v_org_id and role <> 'admin'::public.app_role),
      'page_permissions',(select count(*) from public.page_permissions pp where pp.organization_id=v_org_id and exists(select 1 from public.profiles p where p.id=pp.profile_id and p.role <> 'admin'::public.app_role))
    );
  end if;
  return v_result;
end;
$$;

create or replace function public.export_clinic_reset_backup_json(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid := nullif(p_payload->>'organization_id', '')::uuid;
  v_mode text := coalesce(nullif(p_payload->>'reset_mode', ''), 'full');
  v_from date := nullif(p_payload->>'date_from', '')::date;
  v_to date := nullif(p_payload->>'date_to', '')::date;
  v_groups text[] := coalesce(array(select jsonb_array_elements_text(p_payload->'groups')), array[]::text[]);
  v_result jsonb := '{}'::jsonb;
begin
  if not public.is_software_owner() then raise exception 'Only software owner can export clinic backup'; end if;
  if v_org_id is null then raise exception 'Clinic is required'; end if;
  if v_mode <> 'full' and (v_from is null or v_to is null) then raise exception 'Date range is required'; end if;
  if v_mode <> 'full' and (
    public.reset_has_group(v_groups,'patients') or public.reset_has_group(v_groups,'products') or
    public.reset_has_group(v_groups,'suppliers') or public.reset_has_group(v_groups,'doctors') or
    public.reset_has_group(v_groups,'non_admin_users')
  ) then
    raise exception 'Patient, product, supplier, doctor and user master data can only be exported in full reset';
  end if;

  if public.reset_has_group(v_groups,'sales') then
    v_result := v_result || jsonb_build_object(
      'sales',coalesce((select jsonb_agg(to_jsonb(s) order by s.sold_at desc) from public.sales s where s.organization_id=v_org_id and (v_mode='full' or s.sold_at::date between v_from and v_to)),'[]'::jsonb),
      'sale_items',coalesce((select jsonb_agg(to_jsonb(si)) from public.sale_items si where si.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.sales s where s.id=si.sale_id and s.sold_at::date between v_from and v_to))),'[]'::jsonb),
      'payments',coalesce((select jsonb_agg(to_jsonb(p) order by p.paid_at desc) from public.payments p where p.organization_id=v_org_id and (v_mode='full' or p.paid_at::date between v_from and v_to)),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'purchases') then
    v_result := v_result || jsonb_build_object(
      'purchases',coalesce((select jsonb_agg(to_jsonb(p) order by p.invoice_date desc) from public.purchases p where p.organization_id=v_org_id and (v_mode='full' or p.invoice_date between v_from and v_to)),'[]'::jsonb),
      'purchase_items',coalesce((select jsonb_agg(to_jsonb(pi)) from public.purchase_items pi where pi.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.purchases p where p.id=pi.purchase_id and p.invoice_date between v_from and v_to))),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'patient_history') then
    v_result := v_result || jsonb_build_object(
      'consultations',coalesce((select jsonb_agg(to_jsonb(c) order by c.visited_at desc) from public.consultations c where c.organization_id=v_org_id and (v_mode='full' or c.visited_at::date between v_from and v_to)),'[]'::jsonb),
      'prescription_attachments',coalesce((select jsonb_agg(to_jsonb(pa)) from public.prescription_attachments pa where pa.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.consultations c where c.id=pa.consultation_id and c.visited_at::date between v_from and v_to))),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'inventory') then
    v_result := v_result || jsonb_build_object(
      'stock_movements',coalesce((select jsonb_agg(to_jsonb(sm) order by sm.occurred_at desc) from public.stock_movements sm where sm.organization_id=v_org_id and (v_mode='full' or sm.occurred_at::date between v_from and v_to)),'[]'::jsonb),
      'medicine_batches',coalesce((select jsonb_agg(to_jsonb(mb)) from public.medicine_batches mb where mb.organization_id=v_org_id and v_mode='full'),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'patients') then v_result := v_result || jsonb_build_object('patients',coalesce((select jsonb_agg(to_jsonb(p)) from public.patients p where p.organization_id=v_org_id),'[]'::jsonb)); end if;
  if public.reset_has_group(v_groups,'products') then v_result := v_result || jsonb_build_object('products',coalesce((select jsonb_agg(to_jsonb(p)) from public.products p where p.organization_id=v_org_id),'[]'::jsonb)); end if;
  if public.reset_has_group(v_groups,'suppliers') then v_result := v_result || jsonb_build_object('suppliers',coalesce((select jsonb_agg(to_jsonb(s)) from public.suppliers s where s.organization_id=v_org_id),'[]'::jsonb)); end if;
  if public.reset_has_group(v_groups,'supplier_accounts') then
    v_result := v_result || jsonb_build_object(
      'supplier_payments',coalesce((select jsonb_agg(to_jsonb(sp) order by sp.paid_on desc) from public.supplier_payments sp where sp.organization_id=v_org_id and (v_mode='full' or sp.paid_on between v_from and v_to)),'[]'::jsonb),
      'supplier_ledger',coalesce((select jsonb_agg(to_jsonb(sl) order by sl.occurred_on desc) from public.supplier_ledger sl where sl.organization_id=v_org_id and (v_mode='full' or sl.occurred_on between v_from and v_to)),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'cash_ledger') then
    v_result := v_result || jsonb_build_object(
      'cash_ledger',coalesce((select jsonb_agg(to_jsonb(cl) order by cl.occurred_at desc) from public.cash_ledger cl where cl.organization_id=v_org_id and (v_mode='full' or cl.occurred_at::date between v_from and v_to)),'[]'::jsonb),
      'daily_closings',coalesce((select jsonb_agg(to_jsonb(dc) order by dc.closing_date desc) from public.daily_closings dc where dc.organization_id=v_org_id and (v_mode='full' or dc.closing_date between v_from and v_to)),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'accounting') then
    v_result := v_result || jsonb_build_object(
      'journal_entries',coalesce((select jsonb_agg(to_jsonb(je) order by je.entry_date desc) from public.journal_entries je where je.organization_id=v_org_id and (v_mode='full' or je.entry_date between v_from and v_to)),'[]'::jsonb),
      'journal_lines',coalesce((select jsonb_agg(to_jsonb(jl)) from public.journal_lines jl where jl.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.journal_entries je where je.id=jl.journal_entry_id and je.entry_date between v_from and v_to))),'[]'::jsonb),
      'account_ledgers',coalesce((select jsonb_agg(to_jsonb(al)) from public.account_ledgers al where al.organization_id=v_org_id and v_mode='full'),'[]'::jsonb),
      'ledger_groups',coalesce((select jsonb_agg(to_jsonb(lg)) from public.ledger_groups lg where lg.organization_id=v_org_id and v_mode='full'),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'expenses') then v_result := v_result || jsonb_build_object('expenses',coalesce((select jsonb_agg(to_jsonb(e) order by e.expense_date desc) from public.expenses e where e.organization_id=v_org_id and (v_mode='full' or e.expense_date between v_from and v_to)),'[]'::jsonb)); end if;
  if public.reset_has_group(v_groups,'deleted_audit') then
    v_result := v_result || jsonb_build_object(
      'deleted_sales_audit',coalesce((select jsonb_agg(to_jsonb(d) order by d.deleted_at desc) from public.deleted_sales_audit d where d.organization_id=v_org_id and (v_mode='full' or d.deleted_at::date between v_from and v_to)),'[]'::jsonb),
      'deleted_purchases_audit',coalesce((select jsonb_agg(to_jsonb(d) order by d.deleted_at desc) from public.deleted_purchases_audit d where d.organization_id=v_org_id and (v_mode='full' or d.deleted_at::date between v_from and v_to)),'[]'::jsonb)
    );
  end if;
  if public.reset_has_group(v_groups,'notifications') then v_result := v_result || jsonb_build_object('notifications',coalesce((select jsonb_agg(to_jsonb(n)) from public.notifications n where n.organization_id=v_org_id),'[]'::jsonb)); end if;
  if public.reset_has_group(v_groups,'doctors') then v_result := v_result || jsonb_build_object('doctors',coalesce((select jsonb_agg(to_jsonb(d)) from public.doctors d where d.organization_id=v_org_id),'[]'::jsonb)); end if;
  if public.reset_has_group(v_groups,'non_admin_users') then
    v_result := v_result || jsonb_build_object('profiles', coalesce((select jsonb_agg(to_jsonb(p)) from public.profiles p where p.organization_id = v_org_id), '[]'::jsonb));
    v_result := v_result || jsonb_build_object('user_invites', coalesce((select jsonb_agg(to_jsonb(ui)) from public.user_invites ui where ui.organization_id = v_org_id), '[]'::jsonb));
    v_result := v_result || jsonb_build_object('page_permissions', coalesce((select jsonb_agg(to_jsonb(pp)) from public.page_permissions pp where pp.organization_id = v_org_id), '[]'::jsonb));
  end if;
  return v_result;
end;
$$;

create or replace function public.execute_clinic_reset_json(p_payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid := nullif(p_payload->>'organization_id', '')::uuid;
  v_mode text := coalesce(nullif(p_payload->>'reset_mode', ''), 'full');
  v_from date := nullif(p_payload->>'date_from', '')::date;
  v_to date := nullif(p_payload->>'date_to', '')::date;
  v_groups text[] := coalesce(array(select jsonb_array_elements_text(p_payload->'groups')), array[]::text[]);
  v_deleted integer := 0;
  v_count integer := 0;
begin
  if not public.is_software_owner() then raise exception 'Only software owner can reset clinic data'; end if;
  if v_org_id is null then raise exception 'Clinic is required'; end if;
  if v_mode <> 'full' and (v_from is null or v_to is null) then raise exception 'Date range is required'; end if;
  if v_mode <> 'full' and (
    public.reset_has_group(v_groups,'patients') or public.reset_has_group(v_groups,'products') or
    public.reset_has_group(v_groups,'suppliers') or public.reset_has_group(v_groups,'doctors') or
    public.reset_has_group(v_groups,'non_admin_users')
  ) then
    raise exception 'Patient, product, supplier, doctor and user master data can only be removed in full reset';
  end if;
  if public.reset_has_group(v_groups,'patients') and not public.reset_has_group(v_groups,'patient_history') then
    raise exception 'Select patient history also before removing patients';
  end if;
  if public.reset_has_group(v_groups,'products') and not public.reset_has_group(v_groups,'inventory') then
    raise exception 'Select inventory also before removing products';
  end if;
  if public.reset_has_group(v_groups,'suppliers') and (not public.reset_has_group(v_groups,'purchases') or not public.reset_has_group(v_groups,'supplier_accounts') or not public.reset_has_group(v_groups,'inventory')) then
    raise exception 'Select purchases, supplier accounts and inventory also before removing suppliers';
  end if;
  if public.reset_has_group(v_groups,'doctors') and not public.reset_has_group(v_groups,'patient_history') then
    raise exception 'Select patient history also before removing doctors';
  end if;

  if public.reset_has_group(v_groups,'accounting') then
    delete from public.journal_lines jl where jl.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.journal_entries je where je.id=jl.journal_entry_id and je.entry_date between v_from and v_to)); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.journal_entries where organization_id=v_org_id and (v_mode='full' or entry_date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'deleted_audit') then
    delete from public.deleted_sales_audit where organization_id=v_org_id and (v_mode='full' or deleted_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.deleted_purchases_audit where organization_id=v_org_id and (v_mode='full' or deleted_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'patient_history') then
    delete from public.prescription_attachments pa where pa.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.consultations c where c.id=pa.consultation_id and c.visited_at::date between v_from and v_to)); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'sales') then
    delete from public.deleted_sales_audit d where d.organization_id=v_org_id and exists(select 1 from public.sales s where s.id=d.sale_id and (v_mode='full' or s.sold_at::date between v_from and v_to)); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.sale_items si where si.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.sales s where s.id=si.sale_id and s.sold_at::date between v_from and v_to)); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.payments where organization_id=v_org_id and (v_mode='full' or paid_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    update public.consultations set doctor_fee_collected_bill_id=null, doctor_fee_collected=false where organization_id=v_org_id and doctor_fee_collected_bill_id in (select id from public.sales where organization_id=v_org_id and (v_mode='full' or sold_at::date between v_from and v_to));
    delete from public.sales where organization_id=v_org_id and (v_mode='full' or sold_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'purchases') then
    delete from public.deleted_purchases_audit d where d.organization_id=v_org_id and exists(select 1 from public.purchases p where p.id=d.purchase_id and (v_mode='full' or p.invoice_date between v_from and v_to)); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.purchase_items pi where pi.organization_id=v_org_id and (v_mode='full' or exists(select 1 from public.purchases p where p.id=pi.purchase_id and p.invoice_date between v_from and v_to)); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'inventory') then
    delete from public.stock_movements where organization_id=v_org_id and (v_mode='full' or occurred_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    if v_mode='full' then delete from public.medicine_batches where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count; end if;
  end if;
  if public.reset_has_group(v_groups,'purchases') then
    update public.medicine_batches set purchase_id=null where organization_id=v_org_id and purchase_id in (select id from public.purchases where organization_id=v_org_id and (v_mode='full' or invoice_date between v_from and v_to));
    delete from public.purchases where organization_id=v_org_id and (v_mode='full' or invoice_date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'supplier_accounts') then
    delete from public.supplier_ledger where organization_id=v_org_id and (v_mode='full' or occurred_on between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.supplier_payments where organization_id=v_org_id and (v_mode='full' or paid_on between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'cash_ledger') then
    delete from public.cash_ledger where organization_id=v_org_id and (v_mode='full' or occurred_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.daily_closings where organization_id=v_org_id and (v_mode='full' or closing_date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'expenses') then
    delete from public.expenses where organization_id=v_org_id and (v_mode='full' or expense_date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'patient_history') then
    delete from public.consultations where organization_id=v_org_id and (v_mode='full' or visited_at::date between v_from and v_to); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'patients') then
    update public.sales set patient_id=null where organization_id=v_org_id and patient_id in (select id from public.patients where organization_id=v_org_id);
    delete from public.patients where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'suppliers') then
    update public.medicine_batches set supplier_id=null where organization_id=v_org_id and supplier_id in (select id from public.suppliers where organization_id=v_org_id);
    delete from public.suppliers where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'products') then
    delete from public.products where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'accounting') and v_mode='full' then
    delete from public.account_ledgers where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.ledger_groups where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'notifications') then
    delete from public.notifications where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'doctors') then
    update public.user_invites set doctor_id=null where organization_id=v_org_id and doctor_id in (select id from public.doctors where organization_id=v_org_id);
    update public.doctors set profile_id=null where organization_id=v_org_id;
    delete from public.doctors where organization_id=v_org_id; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  if public.reset_has_group(v_groups,'non_admin_users') then
    delete from public.page_permissions pp where pp.organization_id=v_org_id and exists(select 1 from public.profiles p where p.id=pp.profile_id and p.role <> 'admin'::public.app_role); get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.profiles where organization_id=v_org_id and role <> 'admin'::public.app_role; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
    delete from public.user_invites where organization_id=v_org_id and role <> 'admin'::public.app_role; get diagnostics v_count = row_count; v_deleted := v_deleted + v_count;
  end if;
  insert into public.audit_logs(organization_id,user_id,action,module,record_id,new_value)
  values (v_org_id, auth.uid(), 'clinic_reset', 'clinic_management', v_org_id::text, p_payload || jsonb_build_object('deleted_rows', v_deleted));
  return v_deleted;
end;
$$;

revoke all on function public.preview_clinic_reset_json(jsonb) from public;
revoke all on function public.export_clinic_reset_backup_json(jsonb) from public;
revoke all on function public.execute_clinic_reset_json(jsonb) from public;
grant execute on function public.preview_clinic_reset_json(jsonb) to authenticated;
grant execute on function public.export_clinic_reset_backup_json(jsonb) to authenticated;
grant execute on function public.execute_clinic_reset_json(jsonb) to authenticated;

drop policy if exists prescriptions_owner_read on storage.objects;
create policy prescriptions_owner_read on storage.objects for select to authenticated using (
  bucket_id = 'prescriptions' and public.is_software_owner()
);

drop policy if exists prescriptions_owner_delete on storage.objects;
create policy prescriptions_owner_delete on storage.objects for delete to authenticated using (
  bucket_id = 'prescriptions' and public.is_software_owner()
);
