# -*- coding: utf-8 -*-
import codecs
import re

path = 'app/v2/components/PharmacyWorkflows.tsx'
with codecs.open(path, 'r', 'utf-8') as f:
    code = f.read()

printable_invoice_comp = """
// --- Added Printable Invoice Component ---
function PrintableInvoice({ 
  organization, 
  patientName, 
  patientId, 
  mobile, 
  invoiceNo, 
  date, 
  cart, 
  medicine, 
  tax, 
  specialDiscountAmount, 
  total,
  pendingFee,
  title
}: any) {
  return (
    <div className="print-only">
      <div className="print-header">
        <h1>{organization?.clinic_name || organization?.pharmacy_name || "CLINIC / PHARMACY"}</h1>
        <p>{organization?.address || "Address not provided"}</p>
        <p>Phone: {organization?.phone || "-"} | GST: {organization?.gst_number || "Unregistered"}</p>
      </div>

      <div className="print-details">
        <div className="patient-info">
          <strong>Bill To:</strong><br />
          {patientName || "Walk-in Patient"}<br />
          {patientId ? `ID: ${patientId}` : ""}<br />
          {mobile ? `Phone: ${mobile}` : ""}
        </div>
        <div className="invoice-info">
          <h2>{title || "TAX INVOICE"}</h2>
          <strong>Invoice No:</strong> {invoiceNo || "Draft"}<br />
          <strong>Date:</strong> {date ? new Date(date).toLocaleString() : new Date().toLocaleString()}
        </div>
      </div>

      <table className="print-table">
        <thead>
          <tr>
            <th>S.No</th>
            <th>Item / Medicine</th>
            <th>Batch</th>
            <th className="right">Qty</th>
            <th className="right">Rate</th>
            <th className="right">GST</th>
            <th className="right">Total</th>
          </tr>
        </thead>
        <tbody>
          {cart.map((item: any, i: number) => (
            <tr key={i}>
              <td>{i + 1}</td>
              <td>{item.name}</td>
              <td>{item.batch_number}</td>
              <td className="right">{item.qty}</td>
              <td className="right">{Number(item.selling_rate).toFixed(2)}</td>
              <td className="right">{item.gst_percent || 0}%</td>
              <td className="right">{(Number(item.selling_rate) * Number(item.qty)).toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <table className="print-totals">
        <tbody>
          <tr>
            <td>Subtotal:</td>
            <td>{medicine.toFixed(2)}</td>
          </tr>
          {tax > 0 && <tr>
            <td>Tax (GST):</td>
            <td>{tax.toFixed(2)}</td>
          </tr>}
          {specialDiscountAmount > 0 && <tr>
            <td>Special Discount:</td>
            <td>-{specialDiscountAmount.toFixed(2)}</td>
          </tr>}
          {pendingFee > 0 && <tr>
            <td>Pending Doctor Fee:</td>
            <td>{pendingFee.toFixed(2)}</td>
          </tr>}
          <tr className="total-row">
            <td>Grand Total:</td>
            <td>{(total + pendingFee).toFixed(2)}</td>
          </tr>
        </tbody>
      </table>
      <div className="print-clear"></div>
      
      <div className="print-footer">
        <p>Thank you for visiting! Wishing you a speedy recovery.</p>
        <p>Generated by {organization?.clinic_name || "Siva Clinic Software"}</p>
      </div>
    </div>
  );
}
"""

if "PrintableInvoice" not in code:
    code = code.replace("export function BillingWorkflow", printable_invoice_comp + "\nexport function BillingWorkflow")

# Now inject <PrintableInvoice /> into BillingWorkflow and InpatientBillingWorkflow, and wrap the rest in <div className="no-print">
# For BillingWorkflow:
code = re.sub(
    r'(return <div>)(<div className="page-head" style=\{\{ display: \'flex\', justifyContent: \'space-between\', alignItems: \'flex-start\' \}\}><div><h1>Billing)',
    r'\1<PrintableInvoice organization={organization} patientName={product ? "Patient" : ""} patientId={patientId} mobile={""} invoiceNo={""} date={""} cart={cart} medicine={medicine} tax={tax} specialDiscountAmount={specialDiscountAmount} total={total} pendingFee={pendingFee} title="PHARMACY INVOICE" /><div className="no-print">\2',
    code
)
# Wait, pendingFee isn't defined simply as `pendingFee` in BillingWorkflow. It's: `pending.reduce((sum, row) => sum + Number(row.doctor_fee || 0), 0)`
# Let's fix that.

code = code.replace(
    'pendingFee={pendingFee}',
    'pendingFee={pending.reduce((sum, row) => sum + Number(row.doctor_fee || 0), 0)}'
)
# And close the no-print div for BillingWorkflow!
code = code.replace('quantity.</p></div>}</div></div>;', 'quantity.</p></div>}</div></div></div>;')


# For InpatientBillingWorkflow:
code = re.sub(
    r'(return <div>)(<div className="page-head" style=\{\{ display: \'flex\', justifyContent: \'space-between\', alignItems: \'flex-start\' \}\}><div><h1>Inpatient Billing)',
    r'\1<PrintableInvoice organization={organization} patientName={""} patientId={patientId} mobile={""} invoiceNo={""} date={""} cart={cart} medicine={medicine} tax={tax} specialDiscountAmount={specialDiscountAmount} total={total} pendingFee={0} title="INPATIENT BILLING" /><div className="no-print">\2',
    code
)
# And close the no-print div for InpatientBillingWorkflow!
code = code.replace('quantity.</p></div>}</div></div>;', 'quantity.</p></div>}</div></div></div>;')

with codecs.open(path, 'w', 'utf-8') as f:
    f.write(code)
print("Updated PharmacyWorkflows.tsx with PrintableInvoice")
