import { ModuleConfig } from "./types";

export const pageSizeOptions = [25, 50, 100, 200];

export type V2NavItem = { label?: string; title?: string; key?: string };

export const v2Nav: V2NavItem[] = [
  { label: "Dashboard", key: "dashboard" },
  { title: "CLINIC" },
  { label: "Patients", key: "patients" },
  { label: "Consultation", key: "consultation" },
  { label: "Patient History", key: "patient-history" },
  { label: "Doctor Fees Pending", key: "doctor-fees-pending" },
  { label: "Follow-up Alerts", key: "follow-up-alerts" },
  { label: "Doctors", key: "doctors" },
  { title: "PHARMACY" },
  { label: "Billing", key: "billing" },
  { label: "Sales", key: "sales" },
  { label: "Medicine Sales", key: "medicine-sales" },
  { label: "Medicine", key: "medicine" },
  { label: "Inventory", key: "inventory" },
  { label: "Low Stock", key: "low-stock" },
  { label: "Rate Edit Verification", key: "rate-edit-verification" },
  { title: "INPATIENT" },
  { label: "Inpatient Billing", key: "inpatient-billing" },
  { label: "Inpatient Payment", key: "inpatient-payment" },
  { label: "Inpatient Ledger", key: "inpatient-ledger" },
  { label: "Expiry Alerts", key: "expiry-alerts" },
  { title: "PURCHASES" },
  { label: "AI Bill Import", key: "purchase-import" },
  { label: "Product Mappings", key: "product-mappings" },
  { label: "New Purchase", key: "new-purchase" },
  { label: "Purchase History", key: "purchase-history" },
  { label: "Suppliers", key: "suppliers" },
  { label: "Supplier Payments", key: "supplier-payments" },
  { label: "Supplier Ledger", key: "supplier-ledger" },
  { label: "Deleted Bills Audit", key: "deleted-bills-audit" },
  { title: "ACCOUNTS" },
  { label: "Day Book", key: "day-book" },
  { label: "Cash Ledger", key: "cash-ledger" },
  { label: "Sales Account", key: "sales-account" },
  { label: "Expense Entry", key: "expense-entry" },
  { label: "Ledger Creation", key: "ledger-creation" },
  { label: "Ledger Statement", key: "ledger-statement" },
  { label: "Ledger Group", key: "ledger-group" },
  { label: "Current Balance", key: "current-balance" },
  { label: "Balance Sheet", key: "balance-sheet" },
  { label: "Profit & Loss", key: "profit-loss" },
  { label: "Reports", key: "reports" },
  { title: "ADMINISTRATION" },
  { label: "Users & Roles", key: "users-roles" },
  { label: "Settings", key: "settings" },
];

export const v2Modules: ModuleConfig[] = [
  {
    key: "medicine",
    navLabel: "Medicine",
    title: "Medicine",
    subtitle: "Database-paginated medicine master",
    table: "products",
    select: "id,product_id,name,barcode,generic_name,category,sale_unit,purchase_unit,default_units_per_purchase_unit,selling_rate,mrp,minimum_stock,active,created_at",
    idPrefix: "MED",
    orderBy: "name",
    ascending: true,
    searchColumns: ["product_id", "name", "barcode", "generic_name", "category"],
    columns: [["product_id", "Medicine ID"], ["name", "Medicine"], ["generic_name", "Generic"], ["category", "Category"], ["sale_unit", "Sale unit"], ["purchase_unit", "Purchase unit"], ["selling_rate", "Rate"], ["mrp", "MRP"], ["minimum_stock", "Minimum stock"], ["active", "Active"]],
    fields: [
      { key: "product_id", label: "Medicine ID", readonlyOnCreate: true },
      { key: "name", label: "Medicine name", required: true },
      { key: "barcode", label: "Barcode" },
      { key: "generic_name", label: "Generic name" },
      { key: "category", label: "Category" },
      { key: "sale_unit", label: "Sale unit", type: "select", options: ["tablet", "capsule", "bottle", "vial", "ampoule", "ml", "gm", "tube", "sachet", "unit"], defaultValue: "tablet" },
      { key: "purchase_unit", label: "Purchase unit", type: "select", options: ["strip", "box", "bottle", "vial", "ampoule", "tube", "sachet", "piece", "unit"], defaultValue: "strip" },
      { key: "default_units_per_purchase_unit", label: "Units / pack", type: "number", defaultValue: 10 },
      { key: "minimum_stock", label: "Minimum stock", type: "number" },
    ],
    filters: [{ key: "active", label: "Status", type: "select", options: [{ label: "Active", value: "true" }, { label: "Inactive", value: "false" }] }],
  },
  {
    key: "patients",
    navLabel: "Patients",
    title: "Patients",
    subtitle: "Database-paginated patient records",
    table: "patients",
    select: "id,patient_id,name,age,gender,mobile,last_visit_at,created_at",
    idPrefix: "PAT",
    orderBy: "created_at",
    ascending: false,
    searchColumns: ["patient_id", "name", "mobile"],
    columns: [["patient_id", "Patient ID"], ["name", "Name"], ["age", "Age"], ["gender", "Gender"], ["mobile", "Mobile"], ["last_visit_at", "Last visit"]],
    fields: [
      { key: "patient_id", label: "Patient ID", readonlyOnCreate: true },
      { key: "name", label: "Patient name", required: true },
      { key: "age", label: "Age", type: "number" },
      { key: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { key: "mobile", label: "Mobile number" },
      { key: "address", label: "Address" },
      { key: "blood_group", label: "Blood group" },
      { key: "allergies", label: "Allergies" },
    ],
  },
  {
    key: "suppliers",
    navLabel: "Suppliers",
    title: "Suppliers",
    subtitle: "Database-paginated supplier master",
    table: "suppliers",
    select: "id,supplier_id,name,mobile,gst_number,drug_license_details,email,address,credit_period_days,created_at",
    idPrefix: "SUP",
    orderBy: "name",
    ascending: true,
    searchColumns: ["supplier_id", "name", "mobile", "gst_number", "email"],
    columns: [["supplier_id", "Supplier ID"], ["name", "Supplier"], ["mobile", "Mobile"], ["gst_number", "GST"], ["credit_period_days", "Credit days"]],
    fields: [
      { key: "supplier_id", label: "Supplier ID", readonlyOnCreate: true },
      { key: "name", label: "Supplier name", required: true },
      { key: "mobile", label: "Mobile" },
      { key: "gst_number", label: "GST number" },
      { key: "drug_license_details", label: "Drug license" },
      { key: "email", label: "Email", type: "email" },
      { key: "address", label: "Address" },
      { key: "credit_period_days", label: "Credit period days", type: "number" },
    ],
  },
  {
    key: "doctors", navLabel: "Doctors", title: "Doctors", subtitle: "Database-paginated doctor master", table: "doctors",
    select: "id,doctor_id,name,qualification,specialization,registration_number,mobile,email,default_fee,active,created_at",
    idPrefix: "DOC", orderBy: "name", ascending: true, searchColumns: ["doctor_id", "name", "mobile", "specialization"],
    columns: [["doctor_id", "Doctor ID"], ["name", "Doctor"], ["specialization", "Specialization"], ["mobile", "Mobile"], ["default_fee", "Default fee"], ["active", "Active"]],
    fields: [{ key: "doctor_id", label: "Doctor ID", readonlyOnCreate: true }, { key: "name", label: "Doctor name", required: true }, { key: "qualification", label: "Qualification" }, { key: "specialization", label: "Specialization" }, { key: "registration_number", label: "Registration number" }, { key: "mobile", label: "Mobile" }, { key: "email", label: "Email", type: "email" }, { key: "default_fee", label: "Default fee", type: "number", defaultValue: 0 }],
    filters: [{ key: "active", label: "Status", type: "select", options: [{ label: "Active", value: "true" }, { label: "Inactive", value: "false" }] }],
  },
  {
    key: "consultation", navLabel: "Consultation", title: "Consultations", subtitle: "Database-paginated consultation register", table: "consultations",
    select: "id,patient_id,doctor_id,visited_at,symptoms,diagnosis,prescription_notes,follow_up_date,doctor_fee,doctor_fee_collected,created_at,patient:patients(patient_id,name,mobile),doctor:doctors(doctor_id,name,mobile,specialization)",
    orderBy: "visited_at", ascending: false, searchColumns: ["symptoms", "diagnosis", "prescription_notes"],
    columns: [["visited_at", "Visit"], ["patient.name", "Patient"], ["doctor.name", "Doctor"], ["symptoms", "Symptoms"], ["diagnosis", "Diagnosis"], ["follow_up_date", "Follow up"], ["doctor_fee", "Doctor fee"], ["doctor_fee_collected", "Collected"]],
    fields: [], editable: false,
    filters: [{ key: "doctor_fee_collected", label: "Fee status", type: "select", options: [{ label: "Collected", value: "true" }, { label: "Pending", value: "false" }] }],
  },
  {
    key: "patient-history", navLabel: "Patient History", title: "Patient History", subtitle: "Database-paginated clinical history", table: "consultations",
    select: "id,patient_id,doctor_id,visited_at,symptoms,diagnosis,clinical_notes,prescription_notes,follow_up_date,doctor_fee,created_at,patient:patients(patient_id,name,mobile),doctor:doctors(doctor_id,name,mobile,specialization)",
    orderBy: "visited_at", ascending: false, searchColumns: ["symptoms", "diagnosis", "clinical_notes", "prescription_notes"],
    columns: [["visited_at", "Visit"], ["patient.name", "Patient"], ["doctor.name", "Doctor"], ["symptoms", "Symptoms"], ["diagnosis", "Diagnosis"], ["clinical_notes", "Clinical notes"], ["prescription_notes", "Prescription"], ["follow_up_date", "Follow up"]],
    fields: [], editable: false,
  },
  {
    key: "doctor-fees-pending", navLabel: "Doctor Fees Pending", title: "Doctor Fees Pending", subtitle: "Uncollected consultation fees", table: "consultations",
    select: "id,patient_id,doctor_id,visited_at,symptoms,diagnosis,doctor_fee,doctor_fee_collected,created_at,patient:patients(patient_id,name,mobile),doctor:doctors(doctor_id,name,mobile,specialization)",
    orderBy: "visited_at", ascending: false, searchColumns: ["symptoms", "diagnosis"],
    columns: [["visited_at", "Visit"], ["patient.name", "Patient"], ["doctor.name", "Doctor"], ["symptoms", "Symptoms"], ["diagnosis", "Diagnosis"], ["doctor_fee", "Doctor fee"]],
    fields: [], editable: false,
    filters: [{ key: "doctor_fee_collected", label: "Fee status", type: "select", options: [{ label: "Pending", value: "false" }, { label: "Collected", value: "true" }] }],
  },
  {
    key: "follow-up-alerts", navLabel: "Follow-up Alerts", title: "Follow-up Alerts", subtitle: "Consultations with follow-up dates", table: "consultations",
    select: "id,patient_id,doctor_id,visited_at,follow_up_date,symptoms,diagnosis,prescription_notes,created_at,patient:patients(patient_id,name,mobile),doctor:doctors(doctor_id,name,mobile,specialization)",
    orderBy: "follow_up_date", ascending: true, searchColumns: ["symptoms", "diagnosis", "prescription_notes"],
    columns: [["follow_up_date", "Follow up"], ["visited_at", "Visit"], ["patient.name", "Patient"], ["doctor.name", "Doctor"], ["symptoms", "Symptoms"], ["diagnosis", "Diagnosis"], ["prescription_notes", "Prescription"]],
    fields: [], editable: false,
  },
  {
    key: "sales", navLabel: "Sales", title: "Sales", subtitle: "Database-paginated sales register", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,medicine_subtotal,medicine_tax,pharmacy_revenue,doctor_fee,grand_total,payment_mode,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["invoice_no", "Invoice"], ["sold_at", "Date"], ["patient.name", "Patient"], ["pharmacy_revenue", "Pharmacy"], ["doctor_fee", "Doctor fee"], ["grand_total", "Total"], ["payment_mode", "Mode"], ["status", "Status"]],
    fields: [], editable: false,
    filters: [{ key: "status", label: "Status", type: "select", options: [{ label: "Completed", value: "completed" }, { label: "Cancelled", value: "cancelled" }] }],
  },
  {
    key: "billing", navLabel: "Billing", title: "Billing", subtitle: "Sales billing register with database-side pagination", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,medicine_subtotal,medicine_tax,doctor_fee,grand_total,payment_mode,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["invoice_no", "Bill"], ["sold_at", "Date"], ["patient.name", "Patient"], ["medicine_subtotal", "Medicine"], ["doctor_fee", "Doctor fee"], ["grand_total", "Total"], ["payment_mode", "Mode"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "medicine-sales", navLabel: "Medicine Sales", title: "Medicine Sales", subtitle: "Pharmacy revenue register", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,pharmacy_revenue,medicine_tax,grand_total,payment_mode,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["invoice_no", "Invoice"], ["sold_at", "Date"], ["patient.name", "Patient"], ["pharmacy_revenue", "Pharmacy revenue"], ["medicine_tax", "Tax"], ["grand_total", "Total"], ["payment_mode", "Mode"]],
    fields: [], editable: false,
  },
  {
    key: "inventory", navLabel: "Inventory", title: "Inventory", subtitle: "Live medicine batch stock", table: "medicine_batches",
    select: "id,batch_number,expiry_date,quantity_received,current_stock,purchase_rate,mrp,selling_rate,gst_percent,rack_location,created_at",
    orderBy: "created_at", ascending: false, searchColumns: ["batch_number", "rack_location"],
    columns: [["batch_number", "Batch"], ["expiry_date", "Expiry"], ["quantity_received", "Received"], ["current_stock", "Stock"], ["purchase_rate", "Purchase"], ["selling_rate", "Selling"], ["mrp", "MRP"], ["rack_location", "Rack"]],
    fields: [], editable: false,
  },
  {
    key: "low-stock", navLabel: "Low Stock", title: "Low Stock", subtitle: "Stock batches for review", table: "medicine_batches",
    select: "id,batch_number,expiry_date,current_stock,mrp,selling_rate,rack_location,created_at",
    orderBy: "current_stock", ascending: true, searchColumns: ["batch_number", "rack_location"],
    columns: [["batch_number", "Batch"], ["current_stock", "Stock"], ["expiry_date", "Expiry"], ["selling_rate", "Selling"], ["mrp", "MRP"], ["rack_location", "Rack"]],
    fields: [], editable: false,
  },
  {
    key: "expiry-alerts", navLabel: "Expiry Alerts", title: "Expiry Alerts", subtitle: "Batches ordered by expiry", table: "medicine_batches",
    select: "id,batch_number,expiry_date,current_stock,mrp,selling_rate,rack_location,created_at",
    orderBy: "expiry_date", ascending: true, searchColumns: ["batch_number", "rack_location"],
    columns: [["expiry_date", "Expiry"], ["batch_number", "Batch"], ["current_stock", "Stock"], ["selling_rate", "Selling"], ["mrp", "MRP"], ["rack_location", "Rack"]],
    fields: [], editable: false,
  },
  {
    key: "purchase-history", navLabel: "Purchase History", title: "Purchase History", subtitle: "Supplier purchase register", table: "purchases",
    select: "id,purchase_no,supplier_invoice_no,invoice_date,invoice_total,amount_paid,balance_payable,status,created_at",
    orderBy: "invoice_date", ascending: false, searchColumns: ["purchase_no", "supplier_invoice_no"],
    columns: [["purchase_no", "Purchase"], ["invoice_date", "Date"], ["supplier_invoice_no", "Supplier invoice"], ["invoice_total", "Total"], ["amount_paid", "Paid"], ["balance_payable", "Balance"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "new-purchase", navLabel: "New Purchase", title: "New Purchase", subtitle: "Recent purchase bills and entry workspace", table: "purchases",
    select: "id,purchase_no,supplier_invoice_no,invoice_date,invoice_total,amount_paid,balance_payable,status,created_at",
    orderBy: "created_at", ascending: false, searchColumns: ["purchase_no", "supplier_invoice_no"],
    columns: [["purchase_no", "Purchase"], ["invoice_date", "Date"], ["supplier_invoice_no", "Supplier invoice"], ["invoice_total", "Total"], ["amount_paid", "Paid"], ["balance_payable", "Balance"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "supplier-payments", navLabel: "Supplier Payments", title: "Supplier Payments", subtitle: "Supplier payment register", table: "supplier_payments",
    select: "id,paid_on,amount,payment_mode,reference_number,remarks,created_at",
    orderBy: "paid_on", ascending: false, searchColumns: ["reference_number", "remarks"],
    columns: [["paid_on", "Date"], ["amount", "Amount"], ["payment_mode", "Mode"], ["reference_number", "Reference"], ["remarks", "Remarks"]],
    fields: [], editable: false,
  },
  {
    key: "supplier-ledger", navLabel: "Supplier Ledger", title: "Supplier Ledger", subtitle: "Supplier debit and credit ledger", table: "supplier_ledger",
    select: "id,occurred_on,particulars,reference_type,reference_number,debit,credit,created_at",
    orderBy: "occurred_on", ascending: false, searchColumns: ["particulars", "reference_type", "reference_number"],
    columns: [["occurred_on", "Date"], ["particulars", "Particulars"], ["reference_type", "Type"], ["reference_number", "Reference"], ["debit", "Debit"], ["credit", "Credit"]],
    fields: [], editable: false,
  },
  {
    key: "cash-ledger", navLabel: "Cash Ledger", title: "Cash Ledger", subtitle: "Cash receipts and payments", table: "cash_ledger",
    select: "id,occurred_at,entry_type,category,reference_type,amount,payment_mode,created_at",
    orderBy: "occurred_at", ascending: false, searchColumns: ["entry_type", "category", "reference_type"],
    columns: [["occurred_at", "Date"], ["entry_type", "Type"], ["category", "Category"], ["reference_type", "Reference"], ["amount", "Amount"], ["payment_mode", "Mode"]],
    fields: [], editable: false,
  },
  {
    key: "expense-entry", navLabel: "Expense Entry", title: "Expense Entry", subtitle: "Expense register", table: "expenses",
    select: "id,expense_date,category,amount,payment_mode,description,created_at",
    orderBy: "expense_date", ascending: false, searchColumns: ["category", "description"],
    columns: [["expense_date", "Date"], ["category", "Category"], ["amount", "Amount"], ["payment_mode", "Mode"], ["description", "Description"]],
    fields: [{ key: "expense_date", label: "Date", type: "date", required: true }, { key: "category", label: "Category", required: true }, { key: "amount", label: "Amount", type: "number", required: true }, { key: "payment_mode", label: "Payment mode", type: "select", options: ["cash", "card", "upi", "bank"], required: true }, { key: "description", label: "Description" }],
  },
  {
    key: "reports", navLabel: "Reports", title: "Reports", subtitle: "Sales report register", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,pharmacy_revenue,doctor_fee,grand_total,payment_mode,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["invoice_no", "Invoice"], ["sold_at", "Date"], ["patient.name", "Patient"], ["pharmacy_revenue", "Pharmacy"], ["doctor_fee", "Doctor fee"], ["grand_total", "Collection"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "day-book", navLabel: "Day Book", title: "Day Book", subtitle: "Chronological journal entries", table: "journal_entries",
    select: "id,voucher_no,voucher_type,entry_date,narration,reference_type,reference_number,created_at",
    orderBy: "entry_date", ascending: false, searchColumns: ["voucher_no", "voucher_type", "narration", "reference_type", "reference_number"],
    columns: [["entry_date", "Date"], ["voucher_no", "Voucher"], ["voucher_type", "Type"], ["narration", "Narration"], ["reference_type", "Reference"], ["reference_number", "Ref no"]],
    fields: [], editable: false,
  },
  {
    key: "sales-account", navLabel: "Sales Account", title: "Sales Account", subtitle: "Sales account register", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,pharmacy_revenue,doctor_fee,grand_total,payment_mode,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["sold_at", "Date"], ["invoice_no", "Invoice"], ["patient.name", "Patient"], ["pharmacy_revenue", "Pharmacy"], ["doctor_fee", "Doctor fee"], ["grand_total", "Total"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "ledger-creation", navLabel: "Ledger Creation", title: "Ledger Creation", subtitle: "Account ledger master", table: "account_ledgers",
    select: "id,name,opening_balance,opening_type,active,created_at",
    orderBy: "name", ascending: true, searchColumns: ["name", "opening_type"],
    columns: [["name", "Ledger"], ["opening_balance", "Opening"], ["opening_type", "Type"], ["active", "Active"], ["created_at", "Created"]],
    fields: [{ key: "name", label: "Ledger name", required: true }, { key: "opening_balance", label: "Opening balance", type: "number", defaultValue: 0 }, { key: "opening_type", label: "Opening type", type: "select", options: ["debit", "credit"], defaultValue: "debit" }],
  },
  {
    key: "ledger-statement", navLabel: "Ledger Statement", title: "Ledger Statement", subtitle: "Journal line register", table: "journal_lines",
    select: "id,ledger_name,debit,credit,line_order,created_at",
    orderBy: "created_at", ascending: false, searchColumns: ["ledger_name"],
    columns: [["created_at", "Date"], ["ledger_name", "Ledger"], ["debit", "Debit"], ["credit", "Credit"], ["line_order", "Line"]],
    fields: [], editable: false,
  },
  {
    key: "ledger-group", navLabel: "Ledger Group", title: "Ledger Group", subtitle: "Account groups", table: "ledger_groups",
    select: "id,name,group_type,created_at",
    orderBy: "name", ascending: true, searchColumns: ["name", "group_type"],
    columns: [["name", "Group"], ["group_type", "Type"], ["created_at", "Created"]],
    fields: [{ key: "name", label: "Group name", required: true }, { key: "group_type", label: "Group type", type: "select", options: ["asset", "liability", "income", "expense", "equity"], required: true }],
  },
  {
    key: "current-balance", navLabel: "Current Balance", title: "Current Balance", subtitle: "Ledger balances from account master", table: "account_ledgers",
    select: "id,name,opening_balance,opening_type,active,created_at",
    orderBy: "name", ascending: true, searchColumns: ["name", "opening_type"],
    columns: [["name", "Ledger"], ["opening_balance", "Opening"], ["opening_type", "Type"], ["active", "Active"]],
    fields: [], editable: false,
  },
  {
    key: "balance-sheet", navLabel: "Balance Sheet", title: "Balance Sheet", subtitle: "Balance sheet ledger base", table: "account_ledgers",
    select: "id,name,opening_balance,opening_type,active,created_at",
    orderBy: "name", ascending: true, searchColumns: ["name", "opening_type"],
    columns: [["name", "Ledger"], ["opening_balance", "Opening"], ["opening_type", "Type"], ["active", "Active"]],
    fields: [], editable: false,
  },
  {
    key: "profit-loss", navLabel: "Profit & Loss", title: "Profit & Loss", subtitle: "Profit and loss sales base", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,pharmacy_revenue,doctor_fee,grand_total,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["sold_at", "Date"], ["invoice_no", "Invoice"], ["patient.name", "Patient"], ["pharmacy_revenue", "Pharmacy"], ["doctor_fee", "Doctor fee"], ["grand_total", "Total"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "inpatient-billing", navLabel: "Inpatient Billing", title: "Inpatient Billing", subtitle: "Inpatient medicine bills", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,grand_total,payment_mode,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["invoice_no", "Bill"], ["sold_at", "Date"], ["patient.name", "Patient"], ["grand_total", "Total"], ["payment_mode", "Mode"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "inpatient-payment", navLabel: "Inpatient Payment", title: "Inpatient Payment", subtitle: "Patient payment register", table: "payments",
    select: "id,paid_at,amount,mode,reference_number,created_at",
    orderBy: "paid_at", ascending: false, searchColumns: ["reference_number"],
    columns: [["paid_at", "Date"], ["amount", "Amount"], ["mode", "Mode"], ["reference_number", "Reference"]],
    fields: [], editable: false,
  },
  {
    key: "inpatient-ledger", navLabel: "Inpatient Ledger", title: "Inpatient Ledger", subtitle: "Patient ledger register", table: "patient_ledger",
    select: "id,occurred_on,particulars,reference_type,reference_number,debit,credit,created_at",
    orderBy: "occurred_on", ascending: false, searchColumns: ["particulars", "reference_type", "reference_number"],
    columns: [["occurred_on", "Date"], ["particulars", "Particulars"], ["reference_type", "Type"], ["reference_number", "Reference"], ["debit", "Debit"], ["credit", "Credit"]],
    fields: [], editable: false,
  },
  {
    key: "rate-edit-verification", navLabel: "Rate Edit Verification", title: "Rate Edit Verification", subtitle: "Bills with rate edits", table: "sales",
    select: "id,invoice_no,patient_id,sold_at,grand_total,rate_edit_verified,rate_edit_verified_at,status,created_at,patient:patients(patient_id,name,mobile)",
    orderBy: "sold_at", ascending: false, searchColumns: ["invoice_no"],
    columns: [["invoice_no", "Invoice"], ["sold_at", "Date"], ["patient.name", "Patient"], ["grand_total", "Total"], ["rate_edit_verified", "Verified"], ["rate_edit_verified_at", "Verified at"], ["status", "Status"]],
    fields: [], editable: false,
  },
  {
    key: "deleted-bills-audit", navLabel: "Deleted Bills Audit", title: "Deleted Bills Audit", subtitle: "Deleted bill audit", table: "deleted_sales_audit",
    select: "id,invoice_no,deleted_at,deleted_by_name,reason,grand_total,created_at",
    orderBy: "deleted_at", ascending: false, searchColumns: ["invoice_no", "deleted_by_name", "reason"],
    columns: [["deleted_at", "Deleted"], ["invoice_no", "Invoice"], ["deleted_by_name", "Deleted by"], ["reason", "Reason"], ["grand_total", "Total"]],
    fields: [], editable: false,
  },
  {
    key: "users-roles", navLabel: "Users & Roles", title: "Users & Roles", subtitle: "Active user profiles", table: "profiles",
    select: "id,username,full_name,role,mobile,active,created_at",
    orderBy: "full_name", ascending: true, searchColumns: ["username", "full_name", "role", "mobile"],
    columns: [["username", "Username"], ["full_name", "Name"], ["role", "Role"], ["mobile", "Mobile"], ["active", "Active"]],
    fields: [], editable: false,
  },
  {
    key: "settings", navLabel: "Settings", title: "Settings", subtitle: "Clinic settings", table: "organizations",
    select: "id,clinic_name,pharmacy_name,phone,gst_number,drug_license_number,sales_gst_mode,active,created_at",
    orderBy: "created_at", ascending: false, searchColumns: ["clinic_name", "pharmacy_name", "phone", "gst_number"],
    columns: [["clinic_name", "Clinic"], ["pharmacy_name", "Pharmacy"], ["phone", "Phone"], ["gst_number", "GST"], ["sales_gst_mode", "GST mode"], ["active", "Active"]],
    fields: [], editable: false, organizationColumn: "id",
  },
];

export function getV2Module(key: string) {
  return v2Modules.find((module) => module.key === key);
}



