export const v2WorkflowPages = new Set([
  "consultation",
  "patient-history",
  "doctor-fees-pending",
  "follow-up-alerts",
  "billing",
  "sales",
  "medicine-sales",
  "inventory",
  "low-stock",
  "rate-edit-verification",
  "inpatient-billing",
  "inpatient-payment",
  "inpatient-ledger",
  "expiry-alerts",
  "purchase-import",
  "product-mappings",
  "new-purchase",
  "purchase-history",
  "supplier-payments",
  "supplier-ledger",
  "deleted-bills-audit",
  "day-book",
  "cash-ledger",
  "sales-account",
  "expense-entry",
  "ledger-creation",
  "ledger-statement",
  "ledger-group",
  "current-balance",
  "balance-sheet",
  "profit-loss",
  "reports",
  "users-roles",
  "settings",
]);

export const v2WorkflowStatus: Record<string, string> = {
  consultation: "Needs form workflow: patient search, doctor selection, consultation save, attachment upload.",
  "patient-history": "Needs patient timeline workflow with attachment viewer and upload.",
  "doctor-fees-pending": "Needs fee collection workflow and sale/journal write.",
  "follow-up-alerts": "Needs date-filtered workflow with prescription attachments.",
  billing: "Needs FEFO cart, stock deduction, sale items, doctor fee collection, journal write.",
  sales: "Needs bill detail, delete/cancel audit, payment detail.",
  "medicine-sales": "Needs product-wise sales aggregation.",
  inventory: "Needs stock movement drill-down.",
  "low-stock": "Needs low-stock query against product minimum stock.",
  "rate-edit-verification": "Needs verify action.",
  "inpatient-billing": "Needs inpatient cart, credit sale, patient ledger write.",
  "inpatient-payment": "Needs payment entry and ledger/cash/journal write.",
  "inpatient-ledger": "Needs patient-filtered running balance.",
  "expiry-alerts": "Needs expiry-window filtering.",
  "new-purchase": "Needs purchase cart, batch creation, supplier ledger, stock movements.",
  "purchase-history": "Needs bill detail/edit/delete workflow.",
  "supplier-payments": "Needs payment form, supplier ledger, cash/bank/journal writes.",
  "supplier-ledger": "Needs supplier-filtered running balance.",
  "deleted-bills-audit": "Needs combined deleted sale/purchase audit.",
  "day-book": "Needs journal drill-down.",
  "cash-ledger": "Needs cash balance summary.",
  "sales-account": "Needs account summary.",
  "expense-entry": "Needs expense form with cash/bank/journal writes.",
  "ledger-creation": "Needs ledger/group linked editor.",
  "ledger-statement": "Needs account/date filtered journal lines.",
  "ledger-group": "Needs group editor and grouped balances.",
  "current-balance": "Needs computed current balances.",
  "balance-sheet": "Needs grouped asset/liability/equity report.",
  "profit-loss": "Needs income/expense report.",
  reports: "Needs report filters and export.",
  "users-roles": "Needs login creation/edit/delete and page permissions.",
  settings: "Needs clinic settings edit.",
};
